version: '{build}'

install:
- cinst cmake
- set PATH=%PATH%;C:\MinGW\bin
- mingw-get update
# For MinGW to work, sh.exe must not be in the path
- rename "C:\Program Files (x86)\Git\bin\sh.exe" "sh2.exe"
- mingw-get install mingw32-gmp

build_script:
- mkdir build
- cd build
- cmake -DGMP_DIR=C:\MinGW ..
- cmake --build .
- ctest
