version: '{build}'
environment:
  global:
    PLATFORMTOOLSET: "v90"
    PLATFORM: "Win32"

install:
- cinst cmake
- appveyor DownloadFile http://mpir.org/mpir-2.7.0.zip
- 7z x mpir-2.7.0.zip > NUL
- msbuild mpir-2.7.0/build.vc10/lib_mpir_gc/lib_mpir_gc.vcxproj /p:Configuration=Release /p:Platform=%PLATFORM% /p:PlatformToolset=%PLATFORMTOOLSET% /verbosity:normal
- dir mpir-2.7.0\lib\%PLATFORM%\Release
- dir mpir-2.7.0\build.vc10\lib_mpir_gc\%PLATFORM%\Release

build_script:
- mkdir build
- cd build
- cmake -DGMP_INCLUDE_DIRS=..\mpir-2.7.0\lib\%PLATFORM%\Release -DGMP_LIBRARIES=..\mpir-2.7.0\build.vc10\lib_mpir_gc\%PLATFORM%\Release ..
- cmake --build .
- ctest
