version: '{build}'

install:
- mkdir deps
- nuget install libgmp_vc120 -OutputDirectory deps -ExcludeVersion
- cinst cmake

build_script:
- mkdir build
- cd build
- cmake -DGMP_DIR=../deps/libgmp_vc120 ..
- cmake --build .
- ctest
