version: '{build}'

install:
- mkdir deps
- nuget install libgmp_vc120 -OutputDirectory deps -ExcludeVersion
- dir deps
- dir deps\libgmp_vc120
- dir deps\libgmp_vc120\build\native\include
- dir deps\libgmp_vc120\build\native\bin
- cinst cmake

build_script:
- mkdir build
- cd build
- cmake -DGMP_DIR=..\deps\libgmp_vc120\build\native ..
- cmake --build .
- ctest
