require 'rubygems'
require 'rubygems/package_task'
require 'bundler'

Bundler::GemHelper.install_tasks

require 'rake'
require 'rake/extensiontask'

Rake::ExtensionTask.new "symengine" do |ext|
    ext.lib_dir = 'lib/symengine'
end

gemspec = eval(IO.read("symengine.gemspec"))

Gem::PackageTask.new(gemspec).define
