require 'rubygems'
require 'rubygems/package_task'
require 'bundler'

Bundler::GemHelper.install_tasks

require 'rake'
require "rake/extensiontask"

Rake::ExtensionTask.new do |ext|
    ext.name = 'symengine'
    ext.ext_dir = 'ext/symengine'
    ext.lib_dir = 'lib/'
    ext.source_pattern = "**/*.{c,cpp, h}"
end

gemspec = eval(IO.read("symengine.gemspec"))

Gem::PackageTask.new(gemspec).define
